kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-ol-day2
  labels:
    app: ol-day2
spec:
  capacity:
    storage: 2Gi
  nfs:
    server: <HOSTNAME>
    path: <HOST_PATH>
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: managed-nfs-storage
  volumeMode: Filesystem
