kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-ol-day2
  namespace: <OPENSHIFT_PROJECT>
spec:
  accessModes:
    - ReadWriteMany
  selector:
    matchLabels:
      app: ol-day2
  resources:
    requests:
      storage: 2Gi
  volumeName: pv-ol-day2
  storageClassName: managed-nfs-storage
  volumeMode: Filesystem
status:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
